# Simple pipeline to run Pytest unit tests on Azure DevOps
# Triggered on every commit to "develop" or "main" branches

# Uses the additional Python package pytest-azurepipelines,
# not part of the main test/requirements.txt file

# Code coverage reporting requires the following addition 
# to the pytest.ini config file, in order to generate HTML
# output:
#
#  [pytest]
#  addopts =
#    --cov-report=html

trigger:
- develop
- main

name: $(Date:yyyyMMdd)$(Rev:.r)

jobs:

- job: 'pytest_unit_tests'

  pool:
    vmImage: 'windows-latest'
    # vmImage: "ubuntu-latest"

  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      pip install -r test/requirements.txt
      pip install pytest-azurepipelines
    displayName: 'Install test dependencies'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install application dependencies'

  - script: |
      python -m pytest
    displayName: 'pytest'
